KB-technologia/FinMate_BE

src/main/java/org/finmate/common/util/OpenAiApi.java
src/main/java/org/finmate/common/util/OpenAiDTO/ContentItem.java
src/main/java/org/finmate/common/util/OpenAiDTO/Format.java
src/main/java/org/finmate/common/util/OpenAiDTO/InputTokensDetails.java
src/main/java/org/finmate/common/util/OpenAiDTO/Metadata.java
src/main/java/org/finmate/common/util/OpenAiDTO/OpenAiResponseDTO.java
src/main/java/org/finmate/common/util/OpenAiDTO/OutputItem.java
src/main/java/org/finmate/common/util/OpenAiDTO/OutputTokensDetails.java
src/main/java/org/finmate/common/util/OpenAiDTO/Reasoning.java
src/main/java/org/finmate/common/util/OpenAiDTO/Text.java
src/main/java/org/finmate/common/util/OpenAiDTO/Usage.java
src/main/java/org/finmate/config/RootConfig.java
src/main/java/org/finmate/product/controller/ProductController.java
src/main/java/org/finmate/product/dto/ProductComparisonResultDTO.java
src/main/java/org/finmate/product/dto/ProductDTO.java
src/main/java/org/finmate/product/service/ProductService.java
src/main/java/org/finmate/product/service/ProductServiceImpl.java

(#9) feature/product-compare -> develop
- 상품 두개 비교 API 개발 완료
- openai 공통 메소드 작성
- 코드 리팩토링 약간 있음

✨ 금융 상품 비교 API 머지 요청

---

build.gradle
src/main/java/org/finmate/product/controller/ProductController.java
src/main/java/org/finmate/product/mapper/ProductMapper.java
src/main/resources/org/finmate/product/mapper/ProductMapper.xml

feature/product-review -> develop
- Jwt로 사용자 주입해서 금융 상품 리뷰 등록 혹은 삭제 가능
- Jackson관련 의존성 설정
- issue: closed #18

✨ 금융 상품 리뷰 추가 기능 개발

---

src/main/java/org/finmate/product/domain/ProductRateVO.java
src/main/java/org/finmate/product/domain/ProductVO.java
src/main/java/org/finmate/product/dto/ProductDTO.java
src/main/resources/org/finmate/product/mapper/ProductMapper.xml

(#42 ) feature/fix-product -> develop
- finantial_product에 url, min_term, max_term 추가
- product_rate 테이블 추가
- 각 수정된 데이터를 따라 API 수정

:sparkles: 새로운 VO 생성 및 데이터 구조 수정

---

src/main/java/org/finmate/product/domain/DepositVO.java
src/main/java/org/finmate/product/domain/PaymentCycle.java
src/main/java/org/finmate/product/domain/ProductVO.java
src/main/java/org/finmate/product/domain/SavingsVO.java
src/main/java/org/finmate/product/dto/ProductDTO.java
src/main/resources/org/finmate/product/mapper/ProductMapper.xml

feature/update-product-db-and-api -> develop
- 예적금 관련 VO 수정
- ProductMapper.xml 쿼리 수정
- closes #42

✨ 예적금 칼럼 및 VO 수정 

---

src/main/java/org/finmate/security/config/SecurityConfig.java

- SecurityConfig에서 .cosr() 추가하여 CORS 차단 해제
#7  feature/login -> develop
이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
SercurityConfig에 CorsFilter 설정 추가 
- .cors() 추가하여 CORS 차단 해제
- CORS요청 추가로 프론트엔드 요청 허용
리뷰어가 특별히 봐주었으면 하는 부분이 있다면 작성해주세요
> 예시) 메서드 XXX의 이름을 더 잘 짓고 싶은데 혹시 좋은 명칭이 있을까요?

:sparkles: : 일반 로그인 CorsFilter 설정 추가

---

src/main/java/org/finmate/product/controller/ProductController.java
src/main/java/org/finmate/product/controller/ProductFilterController.java
src/main/java/org/finmate/security/config/SecurityConfig.java
src/main/resources/org/finmate/product/mapper/ProductMapper.xml

(#50) feature/login-signup -> develop
- 상품 전체 조회 GET api/product
- 상품 필터링 GET api/product/filter
연결 위한 CrossOrigin 추가하였습니다

✨ 프론트 api 연결 위한 CrossOrigin 추가

---

src/main/java/org/finmate/member/controller/MyPageController.java
src/main/java/org/finmate/member/service/MemberService.java
src/main/java/org/finmate/product/mapper/ProductMapper.java
src/main/java/org/finmate/product/service/ProductService.java
src/main/java/org/finmate/product/service/ProductServiceImpl.java
src/main/java/org/finmate/security/config/SecurityConfig.java
src/main/resources/org/finmate/product/mapper/ProductMapper.xml

- closed #49
- `feature/member-review-api → develop` 
- 로그인한 사용자가 작성한 금융 상품 리뷰 조회 API 구현 (`GET /api/member/review`)
- `SecurityContext` 기반 사용자 식별 로직 적용
- Swagger 문서화 적용
.

✨ 사용자 리뷰 조회 API 개발

---

src/main/java/org/finmate/quiz/controller/QuizController.java
src/main/java/org/finmate/quiz/dto/QuizAnswerResponseDTO.java
src/main/java/org/finmate/quiz/service/QuizService.java
src/main/java/org/finmate/quiz/service/QuizServiceImpl.java

(#58 ) refactor/daily-quiz -> develop
1. 퀴즈 API 응답 DTO 추가
2. 퀴즈 정답 검증 서비스 로직 수정

♻️ 일일 금융 퀴즈 정답 검증 로직 수정

---

src/main/java/org/finmate/product/controller/ProductController.java
src/main/java/org/finmate/product/mapper/ProductMapper.java
src/main/java/org/finmate/product/service/ProductService.java
src/main/java/org/finmate/product/service/ProductServiceImpl.java
src/main/resources/org/finmate/product/mapper/ProductMapper.xml

(#18 ) feature/extend-product-review -> develop
- 사용자의 투자성향 + 동물 이름으로 작성자 자동완성
- 이미 등록된 리뷰가 있을 경우 예외처리

:sparkles: 금융 상품 리뷰 등록 수정

---

src/main/java/org/finmate/member/controller/MyProductsController.java

(#56 ) feature/myproducts-> develop
- ClassPathResource를 사용해 resources/dummy/mydata/user_financial_products.json 파일을 그대로 반환
<br>

✨ 사용자 가입 상품 조회 API 구현

---

src/main/java/org/finmate/assessment/controller/AssessmentController.java
src/main/java/org/finmate/member/controller/MyPageController.java
src/main/java/org/finmate/member/dto/UserStatResponseDTO.java
src/main/java/org/finmate/member/service/KakaoService.java
src/main/java/org/finmate/member/service/MemberService.java
src/main/resources/org/finmate/member/mapper/UserInfoMapper.xml

(#5 ) feature/add-user-info-api -> develop
- 토큰을 통해 userId 주입
- 사용자 5대 지표를 반환함

✨ 사용자 스탯 가져오기 API 개발

---

src/main/java/org/finmate/product/service/ProductServiceImpl.java
src/main/resources/org/finmate/product/mapper/ProductMapper.xml

(#81) feature/product-orderby -> develop
예전 deposit 테이블로 수익률 정렬하고 있어서, 수정하였습니다.
조건도 펀드 이외에는 expected_return + bonus_rate로 할 수 있도록 수정하였습니다.

♻️ ProductMapper.xml 쿼리문 수정

---

src/main/java/org/finmate/adapter/mydata/dto/MyDataProductDTO.java
src/main/java/org/finmate/adapter/mydata/dto/MyDataResponseDTO.java
src/main/java/org/finmate/portfolio/controller/PortfolioController.java
src/main/java/org/finmate/portfolio/dto/PortfolioDTO.java
src/main/java/org/finmate/portfolio/mapper/PortfolioMapper.java
src/main/java/org/finmate/portfolio/service/PortfolioService.java
src/main/java/org/finmate/portfolio/service/PortfolioServiceImpl.java
src/main/resources/org/finmate/portfolio/mapper/PortfolioMapper.xml

(#85) feature/portfolio -> develop
과거 이력의 재무 포트폴리오 검색 조건 변경
기존의 DATE 조건을 대신하여 해당 날짜의 00시~ 23:59 데이터 중 가장 최신의 데이터를 가져오도록 변경

♻️재무 포트폴리오 검색 조건 변경

---

src/main/java/org/finmate/attendance/controller/UserAttendanceController.java
src/main/java/org/finmate/attendance/domain/UserAttendanceVO.java
src/main/java/org/finmate/attendance/dto/UserAttendanceDTO.java
src/main/java/org/finmate/attendance/mapper/UserAttendanceMapper.java
src/main/java/org/finmate/attendance/service/UserAttendanceService.java
src/main/java/org/finmate/attendance/service/UserAttendanceServiceImpl.java
src/main/java/org/finmate/config/RootConfig.java
src/main/java/org/finmate/config/ServletConfig.java
src/main/java/org/finmate/member/service/KakaoService.java
src/main/java/org/finmate/security/dto/AuthResultDTO.java
src/main/java/org/finmate/security/handler/LoginSuccessHandler.java
src/main/resources/org/finmate/attendance/mapper/UserAttendanceMapper.xml

(#91 ) feature/add-exp-attendance-api -> develop
- 로그인 했을 때 첫 로그인인지 확인할 수 있도록 각 파라미터 전달
- 사용자의 출석 현황을 받을 수 있는 API 개발
- 사용자가 출석 버튼을 누르면 출석체크를 하는 API 개발
- GET, POST /api/attendance

✨ 로그인 출석체크 API 개발

---

src/main/java/org/finmate/config/RootConfig.java
src/main/java/org/finmate/security/handler/LoginSuccessHandler.java

🐛 사용자 출석값이 널일경우 로그인이 안되는 버그 수정

---

src/main/java/org/finmate/member/service/MemberServiceImpl.java

feature/login-signup -> develop
유저 레벨, 티켓 수 각각 기본 값 1, 0으로 넣었습니다.

♻️ 회원가입 시 레벨,티켓 기본값 넣기

---

src/main/java/org/finmate/product/domain/ProductVO.java
src/main/java/org/finmate/product/dto/ProductDTO.java
src/main/java/org/finmate/product/service/ProductServiceImpl.java

(#63 ) feature/login-signup -> develop
- ProductDTO, ProductVO에 모험성향과 재정체력 타입을 Integer -> Dobule로 변경
- valueTag, speedTags의 각 ENUM 값을 점수로 매핑해서 거리값 사용
- strategyTag 는 기존과 동일. 단, 0 과 1이 바뀌어있던 버그 수정

✨ 추천 로직 보완

---

src/main/java/org/finmate/member/mapper/UserMapper.java
src/main/java/org/finmate/member/service/MemberServiceImpl.java
src/main/resources/org/finmate/member/mapper/UserMapper.xml

feature/login-signup -> develop
회원 탈퇴 시 즐겨찾기 테이블도 userId를 참조하고 있어, 함께 삭제하는 것으로 수정했습니다.

🐛 회원탈퇴 버그 수정(즐겨찾기 테이블 삭제)

---

src/main/java/org/finmate/adapter/mydata/dto/MyDataProductDTO.java
src/main/resources/dummy/mydata/user_financial_products.json
src/main/resources/dummy/products/financial_products.json

(#126 ) feature/mypage-products
1.  마이페이지에 보여줄 상품 속성들을 DTO에 추가 등록
2. 보유중인 마이데이터 상품 속성 수정 및 적금 추가

♻️ 마이데이터 보유 상품 연동

---

src/main/java/org/finmate/character/dto/CharacterResponseDTO.java
src/main/java/org/finmate/character/service/CharacterServiceImpl.java

(#24 ) feature/character-> develop
- CharacterResponseDTO에 캐릭터 ID 필드 추가

✨ CharacterResponseDTO 캐릭터 ID 필드 추가

---

src/main/java/org/finmate/product/service/ProductServiceImpl.java
src/main/resources/application.properties

hotfix/fix-product-compare -> main
- 사용자가 투자 성향 테스트를 안했을 경우 CharacterVo가 null이라 NullPointException 예외가 뜸.
- 조건문을 추가하여 기본 tone(귀여운 키위새)로 동작되게끔 수정

🐛  금융 상품 비교 에러 수정

---

src/main/java/org/finmate/product/service/ProductServiceImpl.java

(#115 ) feature/recommendation -> develop
- 사용자 포트폴리오가 없어도 추천 되도록 수정
- 이상적인 포트폴리오 비율 일부 수정
- 안정형의 비율을 기존 (80, 20, 0, 0) -> (100, 0, 0, 0) 으로 수정
- 안정 추구형의 비율을 기존 (50, 30, 20, 0) -> (70, 20, 10, 0) 으로 수정
- 중립형의 비율을 기존 (20, 40, 40, 0) -> (30, 40, 30, 0) 으로 수정

✨ 추천 로직 수정

---

src/main/java/org/finmate/product/service/ProductServiceImpl.java

(#115 ) feature/recommendation-> develop
전체 상품 페이지에 수익률, 최신순 정렬 추가

✨ 전체 상품 페이지에 수익률, 최신순 정렬 추가
